# Generated by Django 5.2.2 on 2025-06-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_datos_producto_repuesto_suscriptor_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptor',
            old_name='nombre',
            new_name='nombreCompleto',
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
