# Generated by Django 5.2.2 on 2025-06-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_nombre_suscriptor_nombrecompleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='foto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
