# Generated by Django 5.2.2 on 2025-07-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_articulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
