# Generated by Django 5.2.2 on 2025-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_articulos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('repuesto', 'Repuesto')], max_length=10),
        ),
    ]
